### ISSUE TITLE
Power settings does not works with D

### ISSUE THREAD

**Issue by guielec42** [Schnitzel/hass-miner#357] opened 2024-05-19 15:23 UTC
## Version of the custom_component
V1.1.9

## Configuration

```yaml

Échec de l'appel du service number/set_value. Failed to set wattage.

```

## Describe the bug

When i set power in HA I have error. Value set by brain os is updated in HA.

## Debug log

```text

nregistreur: homeassistant.components.websocket_api.http.connection
Source: components/websocket_api/commands.py:239
intégration: Home Assistant WebSocket API ([documentation](https://www.home-assistant.io/integrations/websocket_api), [problèmes](https://github.com/home-assistant/core/issues?q=is%3Aissue+is%3Aopen+label%3A%22integration%3A+websocket_api%22))
S'est produit pour la première fois: 16:55:00 (8 occurrences)
Dernier enregistrement: 17:34:00

    [140236320235968] Unexpected exception
    [140235999475648] Unexpected exception

Traceback (most recent call last):
  File "/usr/src/homeassistant/homeassistant/components/websocket_api/commands.py", line 239, in handle_call_service
    response = await hass.services.async_call(
               ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2738, in async_call
    response_data = await coro
                    ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/core.py", line 2779, in _execute_service
    return await target(service_call)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 975, in entity_service_call
    single_response = await _handle_entity_call(
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/helpers/service.py", line 1047, in _handle_entity_call
    result = await task
             ^^^^^^^^^^
  File "/usr/src/homeassistant/homeassistant/components/number/__init__.py", line 116, in async_set_value
    await entity.async_set_native_value(native_value)
  File "/config/custom_components/miner/number.py", line 117, in async_set_native_value
    raise pyasic.APIError("Failed to set wattage.")
pyasic.errors.APIError: Failed to set wattage.

```

**Comment by b-rowan** [comment] 2024-05-19 16:43
Duplicate of #335

**Comment by guielec42** [comment] 2024-05-20 05:12
OK how to fix it ?

**Comment by b-rowan** [comment] 2024-05-20 05:19
Haven't been able to find a fix yet, I'm thinking it's a quirk with the latest BOS+ versions and gRPC, but I'm not sure what it is yet.

**Comment by b-rowan** [comment] 2024-05-20 05:20
I have made some changes that might help (https://github.com/UpstreamData/pyasic/commit/a30a7263249d87879236d1813792ebfe11594625), so I can try to make a pre-release for testing, but I'm still not sure what the root cause is.

**Comment by guielec42** [comment] 2024-05-20 05:28
Compare to #355 active swith is working properly.
That would be nice, I'm ready to make test and make you feedback.

**Comment by b-rowan** [comment] 2024-05-26 13:34
Can you try with v1.1.10rc1?   You will have to enable pre-releases on the version selection page, but I fixed some issues with gRPC commands so maybe itll help.

**Comment by guielec42** [comment] 2024-05-26 19:36
Hello,

I did it works properly.
When I change power no error and value is well written in miner.
During setup time apply flag is off and become on when miner is back to
pool at new power settings.
Have a nice day ;)

Le dim. 26 mai 2024 à 15:34, Brett Rowan ***@***.***> a
écrit :

**Closed** 2024-08-05 04:09 UTC
