### ISSUE TITLE
Config flow could not be loaded

### ISSUE THREAD

**Issue by a6k** [Schnitzel/hass-miner#397] opened 2024-10-08 11:56 UTC
500 Internal Server Error Server got itself in trouble

**Comment by rosch99** [comment] 2024-10-09 19:02
I had the same problem with HA in a docker environment.

The problem is a missing "pyasic" package.
It can be installed from the cli with "pip install pyasic==0.60.0" (when using docker you have to exec into the container first).
  Be aware there is, at least for now, a dependancy for version 0.60.0 while the latest is 0.60.8
After that restart HA or reboot the container and it should work.

**Comment by b-rowan** [comment] 2024-10-09 19:04
There is a good chance this is related to #393, but I would need logs to verify.

Also, just `pip install pyasic==0.60.8`, there was no breaking changes only big fixes.

**Comment by a6k** [comment] 2024-10-09 23:27
> I had the same problem with HA in a docker environment.
> 
> The problem is a missing "pyasic" package. It can be installed from the cli with "pip install pyasic==0.60.0" (when using docker you have to exec into the container first). Be aware there is, at least for now, a dependancy for version 0.60.0 while the latest is 0.60.8 After that restart HA or reboot the container and it should work.


       ▄██▄           _   _                                    
     ▄██████▄        | | | | ___  _ __ ___   ___               
   ▄████▀▀████▄      | |_| |/ _ \| '_ ` _ \ / _ \              
 ▄█████    █████▄    |  _  | (_) | | | | | |  __/              
▄██████▄  ▄██████▄   |_| |_|\___/|_| |_| |_|\___|          _   
████████  ██▀  ▀██      / \   ___ ___(_)___| |_ __ _ _ __ | |_ 
███▀▀███  ██   ▄██     / _ \ / __/ __| / __| __/ _` | '_ \| __|
██    ██  ▀ ▄█████    / ___ \\__ \__ \ \__ \ || (_| | | | | |_ 
███▄▄ ▀█  ▄███████   /_/   \_\___/___/_|___/\__\__,_|_| |_|\__|
▀█████▄   ███████▀

Welcome to the Home Assistant command line.

System information
  IPv4 addresses for end0:  10.0.0.25/24
  IPv6 addresses for end0:  fd00::4236:cfa8:bfce:f62f/64, fe80::cf40:c269:92de:6b0f/64
  IPv4 addresses for wlan0: 

  OS Version:               Home Assistant OS 13.1
  Home Assistant Core:      2024.10.1

  Home Assistant URL:       http://homeassistant.local:8123
  Observer URL:             http://homeassistant.local:4357
➜  ~ pip install pyasic==0.60.0
Looking in indexes: https://pypi.org/simple, https://wheels.home-assistant.io/musllinux-index/
Collecting pyasic==0.60.0
  Downloading pyasic-0.60.0-py3-none-any.whl.metadata (11 kB)
Collecting aiofiles>=23.2.1 (from pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/aiofiles-24.1.0-py3-none-any.whl (15 kB)
Collecting asyncssh>=2.14.2 (from pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/asyncssh-2.17.0-py3-none-any.whl (363 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 363.7/363.7 kB 7.6 MB/s eta 0:00:00
Collecting betterproto>=2.0.0b6 (from pyasic==0.60.0)
  Downloading betterproto-2.0.0b7-py3-none-any.whl.metadata (19 kB)
Collecting httpx>=0.26.0 (from pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/httpx-0.27.2-py3-none-any.whl (76 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.4/76.4 kB 26.6 MB/s eta 0:00:00
Collecting passlib>=1.7.4 (from pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/passlib-1.7.4-py2.py3-none-any.whl.metadata (1.7 kB)
Collecting pyaml>=23.12.0 (from pyasic==0.60.0)
  Downloading pyaml-24.9.0-py3-none-any.whl.metadata (11 kB)
Collecting tomli-w==1.0.0 (from pyasic==0.60.0)
  Downloading tomli_w-1.0.0-py3-none-any.whl.metadata (4.9 kB)
Collecting cryptography>=39.0 (from asyncssh>=2.14.2->pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/cryptography-43.0.1-cp39-abi3-musllinux_1_2_aarch64.whl (3.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 3.9/3.9 MB 23.0 MB/s eta 0:00:00
Collecting typing-extensions>=4.0.0 (from asyncssh>=2.14.2->pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/typing_extensions-4.12.2-py3-none-any.whl (37 kB)
Collecting grpclib<0.5.0,>=0.4.1 (from betterproto>=2.0.0b6->pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/grpclib-0.4.7-py3-none-any.whl (76 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 76.2/76.2 kB 25.3 MB/s eta 0:00:00
Collecting python-dateutil<3.0,>=2.8 (from betterproto>=2.0.0b6->pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/python_dateutil-2.9.0.post0-py2.py3-none-any.whl (229 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 229.9/229.9 kB 28.2 MB/s eta 0:00:00
Collecting anyio (from httpx>=0.26.0->pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/anyio-4.6.0-py3-none-any.whl (89 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 89.6/89.6 kB 19.1 MB/s eta 0:00:00
Collecting certifi (from httpx>=0.26.0->pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/certifi-2024.8.30-py3-none-any.whl (167 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 167.3/167.3 kB 22.0 MB/s eta 0:00:00
Collecting httpcore==1.* (from httpx>=0.26.0->pyasic==0.60.0)
  Downloading httpcore-1.0.6-py3-none-any.whl.metadata (21 kB)
Collecting idna (from httpx>=0.26.0->pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/idna-3.10-py3-none-any.whl (70 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 70.4/70.4 kB 23.6 MB/s eta 0:00:00
Collecting sniffio (from httpx>=0.26.0->pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/sniffio-1.3.1-py3-none-any.whl (10 kB)
Collecting h11<0.15,>=0.13 (from httpcore==1.*->httpx>=0.26.0->pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/h11-0.14.0-py3-none-any.whl (58 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 58.3/58.3 kB 19.8 MB/s eta 0:00:00
Requirement already satisfied: PyYAML in /usr/lib/python3.12/site-packages (from pyaml>=23.12.0->pyasic==0.60.0) (6.0.2)
Collecting cffi>=1.12 (from cryptography>=39.0->asyncssh>=2.14.2->pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/cffi-1.17.1-cp312-cp312-musllinux_1_2_aarch64.whl (216 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 216.4/216.4 kB 25.3 MB/s eta 0:00:00
Collecting h2<5,>=3.1.0 (from grpclib<0.5.0,>=0.4.1->betterproto>=2.0.0b6->pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/h2-4.1.0-py3-none-any.whl (57 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 57.5/57.5 kB 16.5 MB/s eta 0:00:00
Collecting multidict (from grpclib<0.5.0,>=0.4.1->betterproto>=2.0.0b6->pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/multidict-6.1.0-cp312-cp312-musllinux_1_2_aarch64.whl (33 kB)
Collecting six>=1.5 (from python-dateutil<3.0,>=2.8->betterproto>=2.0.0b6->pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/six-1.16.0-py2.py3-none-any.whl (11 kB)
Collecting pycparser (from cffi>=1.12->cryptography>=39.0->asyncssh>=2.14.2->pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/pycparser-2.22-py3-none-any.whl (117 kB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 117.6/117.6 kB 17.6 MB/s eta 0:00:00
Collecting hyperframe<7,>=6.0 (from h2<5,>=3.1.0->grpclib<0.5.0,>=0.4.1->betterproto>=2.0.0b6->pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/hyperframe-6.0.1-py3-none-any.whl (12 kB)
Collecting hpack<5,>=4.0 (from h2<5,>=3.1.0->grpclib<0.5.0,>=0.4.1->betterproto>=2.0.0b6->pyasic==0.60.0)
  Downloading https://wheels.home-assistant.io/musllinux-index/hpack-4.0.0-py3-none-any.whl (32 kB)
Downloading pyasic-0.60.0-py3-none-any.whl (398 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 398.6/398.6 kB 14.0 MB/s eta 0:00:00
Downloading tomli_w-1.0.0-py3-none-any.whl (6.0 kB)
Downloading betterproto-2.0.0b7-py3-none-any.whl (105 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 105.4/105.4 kB 19.7 MB/s eta 0:00:00
Downloading httpcore-1.0.6-py3-none-any.whl (78 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 78.0/78.0 kB 19.4 MB/s eta 0:00:00
Downloading https://wheels.home-assistant.io/musllinux-index/passlib-1.7.4-py2.py3-none-any.whl (525 kB)
   ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 525.6/525.6 kB 25.0 MB/s eta 0:00:00
Downloading pyaml-24.9.0-py3-none-any.whl (24 kB)
Installing collected packages: passlib, typing-extensions, tomli-w, sniffio, six, pycparser, pyaml, multidict, idna, hyperframe, hpack, h11, certifi, aiofiles, python-dateutil, httpcore, h2, cffi, anyio, httpx, grpclib, cryptography, betterproto, asyncssh, pyasic
Successfully installed aiofiles-24.1.0 anyio-4.6.0 asyncssh-2.17.0 betterproto-2.0.0b7 certifi-2024.8.30 cffi-1.17.1 cryptography-43.0.1 grpclib-0.4.7 h11-0.14.0 h2-4.1.0 hpack-4.0.0 httpcore-1.0.6 httpx-0.27.2 hyperframe-6.0.1 idna-3.10 multidict-6.1.0 passlib-1.7.4 pyaml-24.9.0 pyasic-0.60.0 pycparser-2.22 python-dateutil-2.9.0.post0 six-1.16.0 sniffio-1.3.1 tomli-w-1.0.0 typing-extensions-4.12.2
WARNING: Running pip as the 'root' user can result in broken permissions and conflicting behaviour with the system package manager. It is recommended to use a virtual environment instead: https://pip.pypa.io/warnings/venv
➜  ~ whoami                            
root
➜  ~


same result:
Error
Config flow could not be loaded: 500 Internal Server Error Server got itself in trouble

**Comment by Johnice73** [comment] 2024-10-10 12:12
same error for me since last HA update in 2024.10

**Comment by TheMoose92** [comment] 2024-10-20 10:55
> I had the same problem with HA in a docker environment.
> 
> The problem is a missing "pyasic" package. It can be installed from the cli with "pip install pyasic==0.60.0" (when using docker you have to exec into the container first). Be aware there is, at least for now, a dependancy for version 0.60.0 while the latest is 0.60.8 After that restart HA or reboot the container and it should work.

Can you explain how i can do this in HA?

**Comment by Schelin78** [comment] 2024-10-20 21:14
Same problem tried downgrading pyasic and tried beta of miner but no luck 🤔

**Comment by oRudi07** [comment] 2024-10-23 06:07
same here

**Comment by MrMattn** [comment] 2024-10-24 12:20
auch bei mir das Problem :-(

was tun?

**Comment by Ben-in-Chicago** [comment] 2024-10-27 13:25
> > I had the same problem with HA in a docker environment.
> > The problem is a missing "pyasic" package. It can be installed from the cli with "pip install pyasic==0.60.0" (when using docker you have to exec into the container first). Be aware there is, at least for now, a dependancy for version 0.60.0 while the latest is 0.60.8 After that restart HA or reboot the container and it should work.
> 
> Downgrading back to 2024.9 works for me as well, but not preferable ofcourse.
> 
> Can you explain how i can do this in HA?

Using the web interface, access the Terminal in Add-Ons. Then paste `ha core update --version 2024.9.3` to downgrade.

**Comment by Schelin78** [comment] 2024-10-28 14:03
Downgrade only way?

**Comment by Schnitzel** [comment] 2024-10-28 14:26
yea, same problem as this: https://github.com/Schnitzel/hass-miner/issues/393#issuecomment-2438171292 see this comment for possible workarounds

closing this.

**Closed by Schnitzel** 2024-10-28 14:26 UTC
