### ISSUE TITLE
Unable to connect to S19Xp with Lux Os 

### ISSUE THREAD

**Issue by helinick81** [Schnitzel/hass-miner#326] opened 2024-02-24 03:25 UTC
Good Evening all
I wish to ask for your assistance. 
I have installed  the latest 1.1.3 got as far as adding the IP of the asic and then the window just stays with no text just the wording 
Submit.  the LuxOs is Luxor Firmware v2024.2.2.175223-e36845d7-1.3.0
Not seeing anything in logs about it. 

I have some auth issues with my Mqtt but i dont think these are relevant 
 [homeassistant.components.mqtt.client] Unable to connect to the MQTT broker: Connection Refused: not authorised.

Look forward to hearing from you 
all the Best

**Comment by UpstreamData** [comment] 2024-02-24 03:27
Submit should be fine, it is interesting though, seems like the password entry is missing. I'll take a look.

**Comment by helinick81** [comment] 2024-02-25 19:47
Has anyone managed to get this to work on a S19 with Lux Os? Seems such a powerful tool I am very surprised not to find any material online.

**Comment by b-rowan** [comment] 2024-02-25 19:56
I think I know what the issue is, the S19 XP w/ LuxOS is unsupported in pyasic, ill get that added there then update this.

**Comment by helinick81** [comment] 2024-02-25 20:05
> I think I know what the issue is, the S19 XP w/ LuxOS is unsupported in pyasic, ill get that added there then update this.

I tried it on the Xp, the K and The new S21.. all on same Lux os Firmware.. all the same issue of just submit button.

**Comment by b-rowan** [comment] 2024-02-25 20:06
Yep, none of those are in the upstream.  Ill add the S21 too.

**Comment by helinick81** [comment] 2024-02-25 20:07
> Yep, none of those are in the upstream. Ill add the S21 too.

fantastic ! look forward to getting up and spreading your good work!

**Comment by b-rowan** [comment] 2024-02-25 20:15
Try with [v1.1.4](https://github.com/Schnitzel/hass-miner/releases/tag/v1.1.4).

**Comment by helinick81** [comment] 2024-02-25 20:26
> Try with [v1.1.4](https://github.com/Schnitzel/hass-miner/releases/tag/v1.1.4).

It came up with uknown error when trying the S21.. below the log

2024-02-25 20:21:32.097 INFO (SyncWorker_10) [homeassistant.util.package] Attempting install of pyasic==0.54.1
2024-02-25 20:22:10.480 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 185, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 358, in async_configure
result = await self._async_configure(flow_id, user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 404, in _async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 501, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/miner/config_flow.py", line 76, in async_step_user
return await self.async_step_login()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/miner/config_flow.py", line 148, in async_step_login
return self.async_create_entry(title=self._data[CONF_TITLE], data=self._data)
~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'title'
2024-02-25 20:22:24.762 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 185, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 358, in async_configure
result = await self._async_configure(flow_id, user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 404, in _async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 501, in _async_handle_step
result: FlowResult = await getattr(flow, method)(user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/miner/config_flow.py", line 76, in async_step_user
return await self.async_step_login()
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/config/custom_components/miner/config_flow.py", line 148, in async_step_login
return self.async_create_entry(title=self._data[CONF_TITLE], data=self._data)
~~~~~~~~~~^^^^^^^^^^^^
KeyError: 'title'

**Comment by helinick81** [comment] 2024-02-25 20:28
same 
Unknown error occurred

on the Xp

**Comment by b-rowan** [comment] 2024-02-25 20:30
Ok interesting.  I'll see what I can do about that.

**Comment by b-rowan** [comment] 2024-02-25 20:44
Wrong step, try v1.1.4rc2

**Comment by helinick81** [comment] 2024-02-25 20:57
same Unknown error occurred

LOG: 


2024-02-25 20:55:23.879 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 185, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 358, in async_configure
result = await self._async_configure(flow_id, user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 404, in _async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 508, in _async_handle_step
if result.get("preview") is not None:
^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'get'
2024-02-25 20:55:23.901 WARNING (MainThread) [py.warnings] /usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py:466: RuntimeWarning: coroutine 'MinerConfigFlow.async_step_title' was never awaited
reset = await self.finish_response(request, resp, start_time)
2024-02-25 20:55:57.310 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 185, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 358, in async_configure
result = await self._async_configure(flow_id, user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 404, in _async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 508, in _async_handle_step
if result.get("preview") is not None:
^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'get'
2024-02-25 20:56:00.962 ERROR (MainThread) [aiohttp.server] Error handling request
Traceback (most recent call last):
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_protocol.py", line 452, in _handle_request
resp = await request_handler(request)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_app.py", line 543, in _handle
resp = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/local/lib/python3.12/site-packages/aiohttp/web_middlewares.py", line 114, in impl
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/security_filter.py", line 91, in security_filter_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/forwarded.py", line 100, in forwarded_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/request_context.py", line 28, in request_context_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/ban.py", line 80, in ban_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/auth.py", line 235, in auth_middleware
return await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/headers.py", line 31, in headers_middleware
response = await handler(request)
^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/view.py", line 149, in handle
result = await handler(request, **request.match_info)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/decorators.py", line 72, in with_admin
return await func(self, request, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/config/config_entries.py", line 185, in post
return await super().post(request, flow_id)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/components/http/data_validator.py", line 72, in wrapper
result = await method(view, request, data, *args, **kwargs)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/helpers/data_entry_flow.py", line 110, in post
result = await self._flow_mgr.async_configure(flow_id, data)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 358, in async_configure
result = await self._async_configure(flow_id, user_input)
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 404, in _async_configure
result = await self._async_handle_step(
^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
File "/usr/src/homeassistant/homeassistant/data_entry_flow.py", line 508, in _async_handle_step
if result.get("preview") is not None:
^^^^^^^^^^
AttributeError: 'coroutine' object has no attribute 'get'

**Comment by helinick81** [comment] 2024-02-25 20:58
both on Xp and S21

**Comment by b-rowan** [comment] 2024-02-25 21:19
Try rc3.

**Comment by helinick81** [comment] 2024-02-25 21:33
![home assistant s21](https://github.com/Schnitzel/hass-miner/assets/41701141/dd780cc1-c8d8-4e83-a18c-713d82c8a1da)
You legend.. it worked on s21... the Hashrate seems a bit strange reading.. I WISH !!!! lol

**Comment by helinick81** [comment] 2024-02-25 21:34
its underclocked at the moment.. it should be 42Th atm

**Comment by b-rowan** [comment] 2024-02-25 21:38
That is quite strange.  I don't have access to a LuxOS miner, especially something that new, so this might be tough to troubleshoot.  What is the real hashrate as compared to the hashrate shown by HASS miner?

**Comment by b-rowan** [comment] 2024-02-25 21:39
It's pretty likely the data is correct just multiplied

**Comment by helinick81** [comment] 2024-02-25 21:44
> That is quite strange. I don't have access to a LuxOS miner, especially something that new, so this might be tough to troubleshoot. What is the real hashrate as compared to the hashrate shown by HASS miner?
Hope this helps ? 
![home assistant s21 comparison values](https://github.com/Schnitzel/hass-miner/assets/41701141/030d56be-f183-4c7e-b692-7f607b5ac55e)

**Comment by helinick81** [comment] 2024-02-25 21:49
XP seems to be reading correct.. its spooling up. give me 5min

**Comment by helinick81** [comment] 2024-02-25 21:57
![home assistant s19XP comparison values](https://github.com/Schnitzel/hass-miner/assets/41701141/c381e022-8042-4146-b7ca-c6db3e92b4d1)
The XP values seem close.. but not sure how often it updates your data. they are close but not exact.. but a lot more accurate than the S21 above

**Comment by b-rowan** [comment] 2024-02-25 22:01
This is where things could get really complicated, are you able to run python scripts at all?

**Comment by b-rowan** [comment] 2024-02-25 22:05
I need the output of this script for each miner, its a powershell script that gets data from it.

To use this, make a new text file, paste this data in, and change the "server" variable at the top to match the IP of your miner. Once that's done, change the file extension of the file to .ps1 (if you cant see this, its in file explore top menu, view, then a checkbox that says file name extensions, then you can rename the file). Right click, select "Run with powershell", then send the result in a text file here.

```
$server = "192.168.1.5"
$port = 4028
$commands = @("summary", "stats")

try {
    foreach ($cmd in $commands) {
        $client = New-Object System.Net.Sockets.TcpClient
        $client.Connect($server, $port)

        $stream = $client.GetStream()

        $command = '{"command": "' + $cmd + '"}'
        $writer = [System.Text.Encoding]::UTF8.GetBytes($command)

        $stream.Write($writer, 0, $writer.Length)
        $stream.Flush()

        # Read response
        $reader = New-Object System.IO.StreamReader($stream)
        $response = $reader.ReadToEnd()
        $reader.Close()

        # Display the response
        Write-Host "Response for command '$cmd':"
        Write-Host "-------------------------------------------------------------------------------------"
        Write-Host $response
        Write-Host ""


        # Clear the stream for the next command
        $stream.Flush()
        # Close the connection
        $client.Close()
    }

    # Wait for a key press
    Read-Host "Press Enter to exit..."
}
catch {
    Write-Host "An error occurred: $_"
    Read-Host "Press Enter to exit..."
}
```

**Comment by helinick81** [comment] 2024-02-25 22:57
[s21 reply.txt](https://github.com/Schnitzel/hass-miner/files/14398155/s21.reply.txt)

**Comment by helinick81** [comment] 2024-02-25 23:01
are these as you need?

**Comment by b-rowan** [comment] 2024-02-25 23:02
Yep, perfect.

**Comment by b-rowan** [comment] 2024-02-25 23:18
Running the data you sent through pyasic seems to work properly...  Not sure where that issue happened, can you try removing those devices and re-adding them?

**Comment by helinick81** [comment] 2024-02-25 23:37
you are right.. it seems to have corrected it self with a fresh re add.... any ideas why the Power limit function is just an unknown indication ? i saw the vid and that was a power slider?

**Comment by b-rowan** [comment] 2024-02-25 23:47
There is no Autotuning capabilities with Luxors firmware, since they don't have a wattage setpoint to my knowledge.

**Comment by helinick81** [comment] 2024-02-25 23:55
there are API commands listed in the docs to change the spec sheet on the fly.. and on lux it does NOT restart when a new setting is selected from list or API 
I they have some sort of tuning.. see attached again
![lux2](https://github.com/Schnitzel/hass-miner/assets/41701141/df49aba5-8920-45e5-a612-22a9475385e0)
![lux1](https://github.com/Schnitzel/hass-miner/assets/41701141/02a7afed-a34a-4298-ba9c-9c9ca69d178b)

**Comment by helinick81** [comment] 2024-02-25 23:57
this is the command to call the list of freqs you set in the sheet 
https://docs.luxor.tech/firmware/api/luxminer/frequencyset

**Comment by b-rowan** [comment] 2024-02-26 00:26
I'm going to close this for now, as that is kindof a separate issue.  For context, I have the same problem in pyasic with Vnish, they have discrete setpoints for wattage and they haven't had the setpoints implemented either, because it makes it really weird when you're using a slider.

**Closed** 2024-02-26 00:26 UTC

**Comment by helinick81** [comment] 2024-02-26 00:30
Thank you very much for all your hard work and effort.
